services:
  app:
    container_name: app-campagnolo
    build: .
    command: node index.js
    ports:
      - "3000:3000"
    volumes:
      - ./server:/var/www
    environment:
      - DB_USER=postgres
      - DB_HOST=db
      - DB_DATABASE=family_db
      - DB_PORT=5432
      - DB_SSL=false
      - DB_PASSWORD=TVy7PXQ3
      - JWT_SECRET=f21f34146de71fa0eba5cbaacaaf1a5b87040d99e04f1dc037c1e08db24ac39d07bec65cccdb42d0875acf77fab9b5910c5e8c3cdc5d4a58ff5db91a2b24556a
  db:
    container_name: db-campagnolo
    image: postgres
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d  # init the db with the sql scripts
    environment:
      - POSTGRES_DB=family_db
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
secrets:
  db-password:
    file: ./db/password.txt